# Demo workflow
name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Print text
        run: echo 'Hello world!'
